package com.modscreating.unlimitedspace.core.stars;

import com.modscreating.unlimitedspace.core.asteroids.AsteroidCluster;
import com.modscreating.unlimitedspace.core.asteroids.AsteroidClusterId;
import com.modscreating.unlimitedspace.core.galaxy.GalacticPosition;
import com.modscreating.unlimitedspace.core.galaxy.layout.SpaceConstants;
import com.modscreating.unlimitedspace.core.planets.Planet;
import com.modscreating.unlimitedspace.core.planets.PlanetDefinition;
import com.modscreating.unlimitedspace.core.planets.PlanetPropertyGenerator;
import com.modscreating.unlimitedspace.core.seed.AsteroidSeed;
import com.modscreating.unlimitedspace.core.seed.PlanetSeed;
import com.modscreating.unlimitedspace.core.seed.Seeds;

import java.util.List;

/**
 * Immutable DATA description of a single star system: stable id, seed,
 * deterministic position and its star(s). Planets are derived lazily by orbit index.
 * This class does NOT create Minecraft dimensions, nor depends on
 * ServerLevel / ChunkGenerator / BlockState.
 */
public final class StarSystem {

    private final StarSystemId id;
    private final long seed;
    private final GalacticPosition position;
    private final List<Star> stars;

    /** Single-star convenience constructor (kept for back-compat). */
    public StarSystem(StarSystemId id, long seed, GalacticPosition position, Star star) {
        this(id, seed, position, List.of(star));
    }

    /** Full constructor: primary star is always {@code stars.get(0)}. */
    public StarSystem(StarSystemId id, long seed, GalacticPosition position, List<Star> stars) {
        this.id = id;
        this.seed = seed;
        this.position = position;
        this.stars = List.copyOf(stars);
    }

    public StarSystemId id() {
        return id;
    }

    public long seed() {
        return seed;
    }

    public StarSystemSeed seedObject() {
        return new StarSystemSeed(seed);
    }

    public GalacticPosition position() {
        return position;
    }

    /** Primary star (first of {@link #stars()}). */
    public Star star() {
        return stars.get(0);
    }

    /**
     * All stars of this system in stable order (1 = single star, 2 = binary,
     * 3 = trinary) as generated by {@link com.modscreating.unlimitedspace.core.stars.StarGenerator#starsFor}.
     */
    public List<Star> stars() {
        return stars;
    }

    /** Planet seed for the given orbit slot; independent of generation order. */
    public long planetSeed(int orbitIndex) {
        return Seeds.planet(seed, orbitIndex);
    }

    /** Planet definition for the given orbit slot (generation order independent). */
    public PlanetDefinition definePlanet(int orbitIndex) {
        PlanetSeed planetSeed = PlanetSeed.forSlot(seed, orbitIndex);
        return PlanetPropertyGenerator.define(planetSeed, id, orbitIndex);
    }

    /** Full generated planet data for the given orbit slot (lazy). */
    public Planet getPlanet(int orbitIndex) {
        PlanetDefinition def = definePlanet(orbitIndex);
        return PlanetPropertyGenerator.generate(def);
    }

    /** Convenience: the moons of the planet at {@code orbitIndex} (domain metadata only). */
    public java.util.List<com.modscreating.unlimitedspace.core.planets.Moon> moons(int orbitIndex) {
        return getPlanet(orbitIndex).moons();
    }

    /** Convenience: moon count of the planet at {@code orbitIndex}. */
    public int moonCount(int orbitIndex) {
        return getPlanet(orbitIndex).moonCount();
    }

    /** A cluster's stable seed for the given cluster index (generation order independent). */
    public long asteroidSeed(int clusterIndex) {
        return Seeds.asteroidField(seed, clusterIndex);
    }

    /**
     * The asteroid cluster at the given cluster index (domain metadata only; never a world).
     * Parent relationship is explicit: the cluster's {@code parentSystem()} == this system's id.
     */
    public AsteroidCluster asteroid(int clusterIndex) {
        return AsteroidCluster.of(AsteroidClusterId.of(id, clusterIndex),
                AsteroidSeed.forSlot(seed, clusterIndex));
    }

    /** Aggregate counts of the whole system, derived purely from the domain model. */
    public record SystemCounts(int stars, int planets, int moons, int asteroidClusters) {}

    /**
     * Deterministic number of planets for this system. Uses the same seed slot as the
     * galaxy-layout placement ({@value 1L}), so it equals the worldgen planet count.
     */
    public int planetCount() {
        return Math.toIntExact(Seeds.rangeLong(seed, 1L, 1L,
                SpaceConstants.MAX_PLANETS_PER_SYSTEM + 1L));
    }

    /** Deterministic number of asteroid clusters for this system (dedicated count slot). */
    public int asteroidClusterCount() {
        return Math.toIntExact(Seeds.rangeLong(seed, 900001L, 1L,
                SpaceConstants.MAX_ASTEROID_CLUSTERS + 1L));
    }

    /**
     * Aggregate counts: stars from {@link #stars()}, planets from {@link #planetCount()},
     * moons summed over every planet of this system, asteroid clusters from
     * {@link #asteroidClusterCount()}. O(#planets) metadata work; never touches worlds.
     */
    public SystemCounts counts() {
        int planets = planetCount();
        int moons = 0;
        for (int orbit = 0; orbit < planets; orbit++) {
            moons += getPlanet(orbit).moonCount();
        }
        return new SystemCounts(stars.size(), planets, moons, asteroidClusterCount());
    }

    @Override
    public String toString() {
        return id.code() + "[" + position() + ", " + star().type() + "]";
    }
}
