package com.modscreating.unlimitedspace.nav;

import com.modscreating.unlimitedspace.core.destination.WorldKind;
import com.modscreating.unlimitedspace.core.galaxy.Galaxy;
import com.modscreating.unlimitedspace.core.nav.DestinationKind;
import com.modscreating.unlimitedspace.core.nav.DestinationResolver;
import com.modscreating.unlimitedspace.core.nav.DestinationSurfacePlayability;
import com.modscreating.unlimitedspace.core.nav.ResolvedDestination;
import com.modscreating.unlimitedspace.cs.ProceduralCsRuntime;
import com.modscreating.unlimitedspace.worldgen.asteroid.AsteroidWorldBinding;
import com.modscreating.unlimitedspace.worldgen.dynamic.DynamicPlanetWorldManager;
import com.modscreating.unlimitedspace.worldgen.planet.MoonWorldBinding;
import com.modscreating.unlimitedspace.worldgen.planet.PlanetWorldBinding;
import com.modscreating.unlimitedspace.worldgen.star.StarWorldBinding;
import com.rae.creatingspace.api.planets.RocketAccessibleDimension;
import com.rae.creatingspace.content.planets.CSDimensionUtil;
import com.rae.creatingspace.content.rocket.RocketContraptionEntity;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;

import java.util.Objects;
import java.util.Optional;

/**
 * Minecraft/CS adapter that turns a raw {@code (system, object, destination)} triple into a
 * fully classified admin navigation result. It delegates all object/destination semantics to
 * the single pure-domain {@link DestinationResolver} and only adds the resource-location
 * mapping and the playability gates (CS registry, LevelStem).
 */
public final class AdminNav {

    private static final org.apache.logging.log4j.Logger LOGGER =
            org.apache.logging.log4j.LogManager.getLogger();

    /**
     * R14.3.1: the addon ships DynamicDimensions 0.9.1 as a hard dependency, so the runtime
     * lazy-world seam is always available; a procedural surface with no static CS entry is
     * therefore {@link DestinationSurfacePlayability#DYNAMIC_PROCEDURAL}.
     */
    private static final boolean DYNAMIC_PROCEDURAL_AVAILABLE = true;

    private AdminNav() {
    }

        /**
     * Resolve the triple against the live {@link Galaxy} and map it to a resource location.
     * System existence is validated via {@link Galaxy#exists(int)} (R14.5 BUG 7A/7B): navigation is
     * NOT bounded by the finite statistics scope, so {@code /nav 5000 ...} resolves directly without
     * materialising systems {@code 0..4999}. This performs domain resolution and the deterministic
     * binding mapping; it does NOT yet check the runtime registries (see
     * {@link #classify(NavResult, DestinationCatalog)}).
     */
    public static NavResult resolveAndMap(Galaxy galaxy,
                                          int system, int object, int destination) {
        Objects.requireNonNull(galaxy, "galaxy");
        if (!galaxy.exists(system)) {
            return NavResult.fail(NavStatus.SYSTEM_NOT_FOUND, NavStatus.SYSTEM_NOT_FOUND.message());
        }
        ResolvedDestination resolved = DestinationResolver.resolve(galaxy, system, object, destination);
        if (resolved.isError()) {
            return NavResult.fail(NavStatus.RESOLVE_ERROR, resolved.errorMessage());
        }
        DestinationKind kind = resolved.destinationKind();
        ResourceLocation rl = null;
        switch (kind) {
            case PLANET_SURFACE:
                rl = PlanetWorldBinding.location(resolved.planet().id(), WorldKind.SURFACE);
                break;
            case PLANET_ORBIT:
                rl = PlanetWorldBinding.location(resolved.planet().id(), WorldKind.ORBIT);
                break;
            case MOON_SURFACE:
                rl = MoonWorldBinding.location(resolved.moon().id(), WorldKind.SURFACE);
                break;
            case MOON_ORBIT:
                rl = MoonWorldBinding.location(resolved.moon().id(), WorldKind.ORBIT);
                break;
            case ASTEROID_FIELD:
                rl = AsteroidWorldBinding.location(resolved.asteroid().id());
                break;
            // R14.9: a star is now a playable SURFACE world (a molten/plasma plane generated by
            // StarChunkGenerator) AND a zero-g ORBIT. STAR_BODY routes to the surface.
            case STAR_BODY:
                rl = StarWorldBinding.location(resolved.star().id().system(), WorldKind.SURFACE);
                break;
            case STAR_ORBIT:
                rl = StarWorldBinding.location(resolved.star().id().system(), WorldKind.ORBIT);
                break;
            default:
                throw new IllegalStateException("unhandled destination kind " + kind);
        }
        return NavResult.ready(resolved, rl);
    }

    /**
     * Apply the playability gates against the runtime catalogs. A {@code OK_READY} result
     * means the destination is registered in both Creating Space and the LevelStem registry.
     */
    public static NavResult classify(NavResult nav, DestinationCatalog catalog) {
        Objects.requireNonNull(nav, "nav");
        Objects.requireNonNull(catalog, "catalog");
        if (nav.status() == NavStatus.STAR_NOT_SUPPORTED) {
            return nav;
        }
        if (nav.isError() || nav.resolved() == null) {
            return nav;
        }
        // R14.4: a body that was already dynamically materialised (or is a static proof world)
        // arrives here as OK_READY from ensureSurface(); its runtime CS travel entry is already
        // registered and the ServerLevel exists, so the static RocketAccessibleDimension/LevelStem
        // datapack gate must NOT reject it. Only unresolved/unsupported or failed bodies proceed.
        if (nav.status() == NavStatus.OK_READY) {
            return nav;
        }
        ResourceLocation rl = nav.resourceLocation();
        if (rl == null) {
            return NavResult.fail(NavStatus.NOT_PLAYABLE, NavStatus.NOT_PLAYABLE.message());
        }
        ResolvedDestination resolved = nav.resolved();
        // PLANET_SURFACE destinations are prepared by ensureSurface() (static proof worlds pass
        // through; procedural worlds are created on demand via DynamicDimensions). classify() is
        // always invoked *after* ensureSurface() in GalaxyCommands.runNav, so a surface that
        // reaches here is already OK_READY (static) or was dynamically created + handed its runtime
        // CS travel entry. The pure playability model governs the gate: STATIC_REGISTERED and
        // DYNAMIC_PROCEDURAL are both playable (the latter must never be rejected by the static
        // csRegistered/hasLevelStem gate BEFORE the dynamic world exists); only DOMAIN_ONLY is an
        // explicit NOT_PLAYABLE failure.
        if (resolved.destinationKind() == DestinationKind.PLANET_SURFACE
                || resolved.destinationKind() == DestinationKind.STAR_BODY) {
            DestinationSurfacePlayability play =
                    DestinationSurfacePlayability.classifyPlanetSurface(
                            catalog.csRegistered(rl), catalog.hasLevelStem(rl), DYNAMIC_PROCEDURAL_AVAILABLE);
            if (play == DestinationSurfacePlayability.STATIC_REGISTERED
                    || play == DestinationSurfacePlayability.DYNAMIC_PROCEDURAL) {
                return nav;
            }
            return NavResult.fail(NavStatus.NOT_PLAYABLE,
                    NavStatus.NOT_PLAYABLE.message() + ": " + rl);
        }
        if (!catalog.csRegistered(rl)) {
            return NavResult.fail(NavStatus.NOT_REGISTERED_IN_CS,
                    NavStatus.NOT_REGISTERED_IN_CS.message() + ": " + rl);
        }
        if (!catalog.hasLevelStem(rl)) {
            return NavResult.fail(NavStatus.NO_LEVEL_STEM,
                    NavStatus.NO_LEVEL_STEM.message() + ": " + rl);
        }
        return NavResult.ready(resolved, rl);
    }

    /**
     * R14.3.1 lazy world creation for admin {@code /nav}.
     *
     * <p>This runs <em>before</em> {@link #classify}'s static Creating Space gate (see
     * {@code GalaxyCommands.runNav}), so a procedural {@link DestinationKind#PLANET_SURFACE} is
     * never rejected by the static {@code RocketAccessibleDimension} registry before the world is
     * created. Two cases:
     * <ul>
     *   <li><b>STATIC_REGISTERED</b> proof worlds ({@code planet_00}..{@code planet_02}) &mdash;
     *       already backed by a datapack dimension + LevelStem &mdash; are passed through untouched;</li>
     *   <li><b>DYNAMIC_PROCEDURAL</b> planet surfaces with no datapack entry are created on first
     *       contact via {@link DynamicPlanetWorldManager#ensurePlanetSurface}, which loads (or
     *       creates) the {@code ServerLevel} and registers the runtime CS travel entry
     *       ({@code registerCsTravelEntry}); the result is then {@code OK_READY}.</li>
     * </ul>
     * Star/moon/asteroid bodies that are not statically registered are left in their classified
     * failure state (no dynamic creation yet).
     */
    public static NavResult ensureSurface(MinecraftServer server, NavResult nav) {
        Objects.requireNonNull(server, "server");
        Objects.requireNonNull(nav, "nav");
        if (nav.isError() || nav.resolved() == null) {
            return nav;
        }
        ResolvedDestination resolved = nav.resolved();
        DestinationKind kind = resolved.destinationKind();
        // R14.9: a star HAS a surface world now, so STAR_BODY proceeds and is lazily materialised
        // by prepareBody below. STAR_ORBIT (a zero-g orbital dimension) also proceeds.
        ResourceLocation rl = nav.resourceLocation();
        if (rl == null) {
            return nav;
        }
        // R14.6.2/14.6.4: guarantee the seed-aware CS metadata for the destination's system exists
        // BEFORE any world preparation. Systems beyond the prebuilt base scope are generated LAZILY
        // (no hard system cap - R14.6.4).
        int systemIndex = resolved.system().id().index();
        if (!ProceduralCsRuntime.ensureSystem(server, systemIndex)) {
            LOGGER.error("[unlimitedspace][MISSING PROCEDURAL CS METADATA] system={} kind={} rl={} "
                            + "stableId={}: could not generate CS metadata",
                    systemIndex, kind, rl, resolved.object() != null ? resolved.object().toString() : "?");
            return NavResult.fail(NavStatus.NOT_PLAYABLE,
                    NavStatus.NOT_PLAYABLE.message() + " (could not generate CS metadata for " + rl + ")");
        }
        // R14.6.4: ALWAYS verify the destination ServerLevel exists before launch. The static proof
        // path (datapack LevelStem) normally has the level loaded at startup, but if it is missing for
        // any reason, fall through to dynamic creation instead of letting the rocket fly and fall back
        // with a missing target level (the "rocket rises then falls" failure).
        DestinationCatalog catalog = CsCatalog.of(server);
        boolean staticRegistered = catalog.csRegistered(rl) && catalog.hasLevelStem(rl);
        net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level> destKey =
                net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.DIMENSION, rl);
        ServerLevel existing = server.getLevel(destKey);
        if (staticRegistered && existing != null) {
            LOGGER.info("[unlimitedspace][NAV] static proof destination confirmed: rl={} kind={} serverLevel={}",
                    rl, kind, existing.getChunkSource().getGenerator().getClass().getSimpleName());
            return NavResult.ready(resolved, rl);
        }
        LOGGER.info("[unlimitedspace][NAV] dynamic world preparation: kind={} rl={} staticRegistered={} levelAlreadyLoaded={}",
                kind, rl, staticRegistered, existing != null);
        long tWorld = System.nanoTime();
        Optional<ServerLevel> level = prepareBody(server, kind, resolved);
        LOGGER.info("[US] world preparation: {} ms (kind={} rl={} ready={})",
                String.format(java.util.Locale.ROOT, "%.1f", (System.nanoTime() - tWorld) / 1_000_000.0),
                kind, rl, level.isPresent());
        if (level.isPresent()) {
            ServerLevel lvl = level.get();
            boolean csRuntime = (CSDimensionUtil.getTravelMap() != null)
                    && CSDimensionUtil.getTravelMap().containsKey(rl);
            String generatorName = lvl.getChunkSource().getGenerator().getClass().getSimpleName();
            LOGGER.info("[unlimitedspace][NAV] after ensureWorld: dynamicWorldReady=true serverLevel=true generator={} runtimeCsEntry={}",
                    generatorName, csRuntime);
            if (!csRuntime) {
                LOGGER.error("[unlimitedspace][MISSING PROCEDURAL CS METADATA] system={} kind={} rl={} "
                                + "stableId={}: world was prepared but the CS runtime travel map has no entry; "
                                + "the flight would silently fall back to gravity 9.81/arrival 64 - refusing to navigate",
                        systemIndex, kind, rl, resolved.object() != null ? resolved.object().toString() : "?");
                return NavResult.fail(NavStatus.NOT_PLAYABLE,
                        NavStatus.NOT_PLAYABLE.message()
                                + " (CS runtime metadata missing for " + rl + "; check csMetadataSystemCount): " + rl);
            }
            return NavResult.ready(resolved, rl);
        }
        LOGGER.warn("[unlimitedspace][NAV] dynamic world could not be loaded: rl={} kind={}", rl, kind);
        return NavResult.fail(NavStatus.NOT_PLAYABLE,
                NavStatus.NOT_PLAYABLE.message() + " (dynamic world could not be loaded): " + rl);
    }

    private static Optional<ServerLevel> prepareBody(MinecraftServer server, DestinationKind kind,
                                                     ResolvedDestination resolved) {
        return switch (kind) {
            case PLANET_SURFACE -> DynamicPlanetWorldManager.ensurePlanetSurface(server, resolved.planet().id());
            case PLANET_ORBIT -> DynamicPlanetWorldManager.ensurePlanetOrbit(server, resolved.planet().id());
            case MOON_SURFACE -> DynamicPlanetWorldManager.ensureMoonSurface(server, resolved.moon().id());
            case MOON_ORBIT -> DynamicPlanetWorldManager.ensureMoonOrbit(server, resolved.moon().id());
            case ASTEROID_FIELD -> DynamicPlanetWorldManager.ensureAsteroidCluster(server, resolved.asteroid().id());
            case STAR_BODY -> DynamicPlanetWorldManager.ensureStarSurface(
                    server, resolved.star().id().system());
            case STAR_ORBIT -> DynamicPlanetWorldManager.ensureStarOrbit(
                    server, resolved.star().id().system());
            default -> Optional.empty();
        };
    }


    /**
     * Hand a fully {@code OK_READY} nav result to the official Creating Space travel bridge for
     * the given player's rocket. Returns a {@code TRAVEL_STARTED} result on success, or an
     * explicit failure ({@code NO_ROCKET} / {@code TRAVEL_BLOCKED}) вЂ” never silent.
     */
    public static NavResult attemptTravel(ServerPlayer player, NavResult nav) {
        Objects.requireNonNull(player, "player");
        Objects.requireNonNull(nav, "nav");
        if (nav.status() != NavStatus.OK_READY) {
            return nav;
        }
        RocketContraptionEntity rocket = CsTravelBridge.findRocket(player);
        if (rocket == null) {
            return NavResult.fail(NavStatus.NO_ROCKET, NavStatus.NO_ROCKET.message());
        }
        ResourceLocation destination = nav.resourceLocation();
        // R14.6.2 trace: the EXACT destination the rocket will fly to, plus the CS runtime values
        // Creating Space will read during handelTrajectoryCalculation and CustomTeleporter.
        Float destGravity = null;
        Integer destArrival = null;
        Boolean destIsOrbit = null;
        try {
            var travelMap = CSDimensionUtil.getTravelMap();
            if (travelMap != null && travelMap.get(destination) != null) {
                var entry = travelMap.get(destination);
                destGravity = entry.gravity();
                destArrival = entry.arrivalHeight();
                destIsOrbit = CSDimensionUtil.isOrbit(destination);
            }
        } catch (Throwable t) {
            LOGGER.warn("[unlimitedspace][NAV] could not read CS runtime values for {}", destination, t);
        }
        LOGGER.info("[unlimitedspace][NAV] rocket destination: rl={} status={} ok={} "
                        + "csGravity={} csArrivalHeight={} csIsOrbit={}",
                destination, nav.status(), nav.ok(),
                destGravity == null ? "MISSING" : destGravity,
                destArrival == null ? "MISSING" : destArrival,
                destIsOrbit == null ? "MISSING" : destIsOrbit);
        // R14.6.5: guarantee the Creating Space cost graph contains the (origin -> destination) route
        // WITHOUT the O(V^2) full rebuild. The route-scoped rebuild is a few ms on the server thread;
        // flight trajectory calculation reads this cost once at launch (handelTrajectoryCalculation).
        ResourceLocation origin = rocket.level().dimension().location();
        long tCost = System.nanoTime();
        boolean costReady = ProceduralCsRuntime.ensureCostRoute(player.server, origin, destination);
        LOGGER.info("[US] cost route: ready={} {} ms (origin={} destination={})",
                costReady, String.format(java.util.Locale.ROOT, "%.1f", (System.nanoTime() - tCost) / 1_000_000.0),
                origin, destination);
        boolean launched = CsTravelBridge.launch(player, rocket, destination);
        if (!launched) {
            return NavResult.fail(NavStatus.TRAVEL_BLOCKED, NavStatus.TRAVEL_BLOCKED.message());
        }
        return NavResult.resolved(NavStatus.TRAVEL_STARTED, null, nav.resolved(),
                nav.resourceLocation());
    }
}
