package com.modscreating.unlimitedspace.cs;

import com.modscreating.unlimitedspace.core.asteroids.AsteroidClusterId;
import com.modscreating.unlimitedspace.core.destination.WorldKind;
import com.modscreating.unlimitedspace.core.planets.MoonId;
import com.modscreating.unlimitedspace.core.planets.PlanetId;
import com.modscreating.unlimitedspace.core.stars.StarSystemId;
import com.modscreating.unlimitedspace.worldgen.planet.PlanetWorldBinding;
import com.modscreating.unlimitedspace.worldgen.star.StarWorldBinding;
import org.junit.jupiter.api.Test;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * R14.6.4: asserts that {@link RocketDestinationWorldWatchdog}'s RL patterns (used to lazily
 * materialise the destination world of ANY in-flight rocket before it crosses the CS Y=300
 * transition) exactly match the deterministic binding paths generated by the world bindings.
 *
 * <p>The test classpath deliberately carries no Minecraft types (see {@code build.gradle}), so
 * every assertion is projected through the pure-domain id {@code code()} seams — the exact path
 * segment the watchdog regexes run against after the {@code unlimitedspace:} namespace is
 * stripped from {@code ResourceLocation.getPath()}.
 */
public final class RocketDestinationWorldWatchdogPatternTest {

    // Mirrors the watchdog patterns (kept here so a mismatch is a test failure).
    private static final Pattern PLANET_RL =
            Pattern.compile("^planet/system_(\\d{4})_planet_(\\d{2})/(surface|orbit)$");
    private static final Pattern MOON_RL =
            Pattern.compile("^moon/system_(\\d{4})_planet_(\\d{2})_moon_(\\d{2})/(surface|orbit)$");
    private static final Pattern ASTEROID_RL =
            Pattern.compile("^asteroid/system_(\\d{4})_asteroid_(\\d{2})$");
    private static final Pattern STAR_RL =
            Pattern.compile("^star/system_(\\d{4})/(surface|orbit)$");

    @Test
    void planetSurfacePathMatchesWatchdogPattern() {
        PlanetId id = PlanetId.of(StarSystemId.of(170), 1);
        String path = PlanetWorldBinding.locationPath(id, WorldKind.SURFACE);
        assertEquals("planet/system_0170_planet_01/surface", path);
        Matcher m = PLANET_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("0170", m.group(1));
        assertEquals("01", m.group(2));
        assertEquals("surface", m.group(3));
    }

    @Test
    void planetOrbitPathMatchesWatchdogPattern() {
        PlanetId id = PlanetId.of(StarSystemId.of(509), 0);
        String path = PlanetWorldBinding.locationPath(id, WorldKind.ORBIT);
        assertEquals("planet/system_0509_planet_00/orbit", path);
        Matcher m = PLANET_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("0509", m.group(1));
        assertEquals("00", m.group(2));
        assertEquals("orbit", m.group(3));
    }

    @Test
    void moonOrbitPathMatchesWatchdogPattern() {
        // The exact RL from the real in-game failure:
        //   unlimitedspace:moon/system_0170_planet_01_moon_03/orbit
        MoonId id = MoonId.of(PlanetId.of(StarSystemId.of(170), 1), 3);
        String path = "moon/" + id.code() + "/orbit";
        assertEquals("moon/system_0170_planet_01_moon_03/orbit", path);
        Matcher m = MOON_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("0170", m.group(1));
        assertEquals("01", m.group(2));
        assertEquals("03", m.group(3));
        assertEquals("orbit", m.group(4));
    }

    @Test
    void moonSurfacePathMatchesWatchdogPattern() {
        MoonId id = MoonId.of(PlanetId.of(StarSystemId.of(0), 3), 0);
        String path = "moon/" + id.code() + "/surface";
        assertEquals("moon/system_0000_planet_03_moon_00/surface", path);
        Matcher m = MOON_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("surface", m.group(4));
    }

    @Test
    void asteroidPathMatchesWatchdogPattern() {
        AsteroidClusterId id = AsteroidClusterId.of(StarSystemId.of(192), 0);
        String path = "asteroid/" + id.code();
        assertEquals("asteroid/system_0192_asteroid_00", path);
        Matcher m = ASTEROID_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("0192", m.group(1));
        assertEquals("00", m.group(2));
    }

    @Test
    void starOrbitPathMatchesWatchdogPattern() {
        String path = StarWorldBinding.locationPath(StarSystemId.of(7), WorldKind.ORBIT);
        assertEquals("star/system_0007/orbit", path);
        Matcher m = STAR_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("0007", m.group(1));
        assertEquals("orbit", m.group(2));
    }

    @Test
    void starSurfacePathMatchesWatchdogPattern() {
        // R14.9: a star surface is a procedurally materialised bound world, so the watchdog must
        // recognise it and lazily create it (otherwise the rocket would rise then fall without a
        // target level, the exact R14.6.4 failure mode).
        String path = StarWorldBinding.locationPath(StarSystemId.of(7), WorldKind.SURFACE);
        assertEquals("star/system_0007/surface", path);
        Matcher m = STAR_RL.matcher(path);
        assertTrue(m.matches(), "watchdog pattern must match " + path);
        assertEquals("0007", m.group(1));
        assertEquals("surface", m.group(2));
    }

    @Test
    void nonProceduralPathsDoNotMatch() {
        assertFalse(PLANET_RL.matcher("minecraft:overworld").matches());
        assertFalse(MOON_RL.matcher("creatingspace:earth_orbit").matches());
        assertFalse(ASTEROID_RL.matcher("planet/system_0000_planet_00/surface").matches());
        assertFalse(PLANET_RL.matcher("planet/system_0000_planet_00/orbitx").matches());
    }

    @Test
    void pathsAreSeedIndependent() {
        // The RL identity (and therefore the watchdog parser) must be identical across seeds;
        // only the gravity/arrival metadata is seed-derived.
        assertEquals("planet/system_0000_planet_00/surface",
                PlanetWorldBinding.locationPath(PlanetId.of(StarSystemId.of(0), 0), WorldKind.SURFACE));
        assertEquals("moon/system_0000_planet_00_moon_00/orbit",
                "moon/" + MoonId.of(PlanetId.of(StarSystemId.of(0), 0), 0).code() + "/orbit");
    }
}
